### GET /
GET http://localhost:5000

### Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMzQyMzA3LCJleHAiOjE3NjI0Mjg3MDd9.91WB2na8D2Xc-c7yFEQJ8UwHql2o7Shf7hAkt4h2zOg

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMzQyMzA3LCJleHAiOjE3NjI0Mjg3MDd9.91WB2na8D2Xc-c7yFEQJ8UwHql2o7Shf7hAkt4h2zOg
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMzQyMzA3LCJleHAiOjE3NjI0Mjg3MDd9.91WB2na8D2Xc-c7yFEQJ8UwHql2o7Shf7hAkt4h2zOg
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMzQxODQ4LCJleHAiOjE3NjI0MjgyNDh9.oLUHakxussdBZ5BlZ6HQAHgs7lQ5wvM7CNjFQW5TyXA
